### ISSUE TITLE
Compile error on Ubuntu 22.04

### ISSUE THREAD

**Issue by gery** [awtterpip/bevy_oxr#138]
error[E0422]: cannot find struct, variant or union type `AmbientLight` in this scope
  --> crates/bevy_openxr/examples/android/src/lib.rs:26:26
   |
26 |         .insert_resource(AmbientLight {
   |                          ^^^^^^^^^^^^ not found in this scope

**Comment by Schmarni-Dev** [comment]
Should be fixed
