### ISSUE TITLE
Panic with directional light shadows

### ISSUE THREAD

**Issue by kayhhh** [awtterpip/bevy_oxr#149]
I get a panic in VR when my directional light has shadows enabled:

```rust
DirectionalLight {
    shadows_enabled: true,
    ..
}
```

The panic is from an unwrap at https://github.com/bevyengine/bevy/blob/d65eb39277c4f85749ba27460b8398f815ef3802/crates/bevy_pbr/src/render/light.rs#L1016

Windows 11
Bevy 0.14.1
Rust 1.80.1

**Comment by ForTehLose** [comment]
The fix for this was just merged.
https://github.com/awtterpip/bevy_oxr/pull/150
closing
