### ISSUE TITLE
Location flags are awkward to access

### ISSUE THREAD

**Issue by Quantum1000** [awtterpip/bevy_oxr#42]
When getting input from the controllers through SpaceLocation and SpaceVelocity, in order to implement a logical default position to account for lack of tracking, it's necessary to check the SpaceLocation.location_flags, to see whether the input is a extrapolation from no tracking, or whether it's live input. Using binary operations  to do this is extremely awkward. In my case, I only wanted to update the state of my system based on the input from the controllers if the location and the orientation was both valid and tracked, so I used the code `(input.0.location_flags.into_raw()&0b1111)^0b1111 == 0`. This is quite awkward. I'm unsure what a better implementation would be, and certainly, even with what's currently present, I could've written a cleaner implementation (for example, 
`let bit_mask = SpaceLocation::OrientationValid | SpaceLocation::PositionValid | SpaceLocation::OrientationTracking | SpaceLocation::PositionTracking`
`(input.0.location_flags.into_raw()&bitmask)^bitmask == 0` would be a more robust implementation).
I haven't actually checked whether OrientationTracking implies OrientationValid, but if so, the best implementation would probably be to be able to access all of these values individually as bools from the SpaceLocation object, and then a bool for both OrientationValid and PositionValid, and finally a bool for OrientationTracking and PositionTracking

**Comment by Schmarni-Dev** [comment]
this is fixed now, location flags are now a component on entities with an XrSpace or in hand joints
